### ISSUE TITLE
Update and clean up README.md 

### ISSUE THREAD

**Issue by albertinadx** [pumascript/puma#12]
The current README.md could be improved in order to add a section for getting started, and then more information like we have today.

**Comment by SidVal** [comment]
You have a markdown error here:
https://github.com/pumascript/puma/blame/master/README.md#L145
Fixed with https://github.com/pumascript/puma/pull/91

**Comment by nestornav** [comment]
We need to add the Puma dependencies sections such as grunt-cli.

**Comment by nestornav** [comment]
This ticket will be closed at the end of code review of this PR #106

**Comment by nestornav** [comment]
Updated #106

**Comment by nestornav** [comment]
#106
