### ISSUE TITLE
Delete parameter "Passed!" in methods ok() and equals() from all tests

### ISSUE THREAD

**Issue by AlanPipino** [pumascript/puma#63]
### From the QUnit  Documentation:

[https://api.qunitjs.com/equal/#equal-actual-expected-message](url)

`equal( actual, expected [, message ] )`

_Description: A non-strict comparison, roughly equivalent to JUnit's assertEquals._
        **actual**         -    Type: Object    -    Expression being tested
        **expected**    -    Type: Object    -    Known comparison value
        **message**     -    Type: String     -    A short description of the assertion

The equal assertion uses the simple comparison operator (==) to compare the actual and expected arguments. When they are equal, the assertion passes; otherwise, it fails. When it fails, both actual and expected values are displayed in the test result, in addition to a given message.

[https://api.qunitjs.com/ok/#ok-state-message](url)

`ok( state [, message ] )`

_Description: A boolean check, equivalent to CommonJS's assert.ok() and JUnit's assertTrue(). Passes if the first argument is truthy._
        **state**    -    Type: Expression    -    Expression being tested
        **message**    -    Type: String    -    A short description of the assertion

The most basic assertion in QUnit, ok() requires just one argument. If the argument evaluates to true, the assertion passes; otherwise, it fails. If a second message argument is provided, it will be displayed in place of the result.

### Meaning
The message arguments are actually optional and are supposed to reflect the purpose of the test. In our case the _test suite_ should be reviewed and for every test this last argument either be **removed or modified** to serve the test objective.

**Comment by Agu-GC** [comment]
I wil be working on that.
