### ISSUE TITLE
Craft a GitHub Pages Website for publishing project information, examples and documentation

### ISSUE THREAD

**Issue by Undre4m** [pumascript/puma#78]
[GitHub Pages](https://pages.github.com/) is an easy and rather complete way of documenting a repositories codebase, providing information about the project and releasing use examples and/or code samples.

Being integrated with the repository it's implementation is quite straightforward and easily maintainable:
[How to publish](https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3), [Docs Setting](https://github.com/blog/2228-simpler-github-pages-publishing)

It's features should be enough for the current implementation as a way of enhancing visibility, providing support and making puma-script more accesible and its use more encouraging.

**Comment by emravera** [comment]
Editor is published in Github pages:

https://github.com/pumascript/pumascript.github.io

URL:
https://pumascript.github.io/
