### ISSUE TITLE
Upgrade current Puma dependencies

### ISSUE THREAD

**Issue by nestornav** [pumascript/puma#98]
Upgrade progressively the major part of pumascript dependencies. We need avoid security issues and take the advantage of new libraries features.

**Comment by consugus** [comment]
This issue is related to issue #93: Migrate Bower Dependencies to NPM. 
As soon as I'm done with issue #93, I'll take care of this too

**Comment by nestornav** [comment]
@consugus  Isn't related with the #93 issue due to these one is focused in update the editor and this is for runtime dependencies. 

@emravera are you keeping working on it?

**Comment by consugus** [comment]
Uppsssss! @nestornav, I missunderstood what this issue was about, and as you explain, it's very complex. Not sure if I can take care of so much

**Comment by emravera** [comment]
I have started this issue I will continue working on this.
